language: php
sudo: required
dist: trusty

jobs:
  include:
    - php: '7.2'
      install:
      - travis_retry pecl install protobuf-3.6.1
      script:
      - ./dev/sh/test-composer-conflict.sh
    - stage: 'deploy'
      php: '7.2'
      install:
      - travis_retry composer install
      script:
      - ./dev/sh/build-docs.sh
      - ./dev/sh/push-docs.sh
      after_success: skip

stages:
  - test
  - name: deploy
    if: ((type != pull_request) AND (branch = master)) OR (tag IS present)

install:
  - travis_retry composer install
