name: Generate Documentation
on:
    push:
        branches:
            - master
        tags:
            - "*"
jobs:
    docs:
        name: "Generate Project Documentation"
        runs-on: ubuntu-16.04
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Generate Documentation
          uses: docker://php:7.2-cli
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          with:
            entrypoint: ./dev/sh/build-docs.sh
        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: gh-pages
            FOLDER: .docs
