name: Test Suite
on:
  push:
    branches:
      - master
  pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 5.5, 5.6, "7.0", 7.1, 7.2, 7.3, 7.4 ]
                proto_c_ext: [ true, false ]

        name: PHP ${{ matrix.php }} Unit Test
        steps:
            - uses: actions/checkout@v2
            - uses: codecov/codecov-action@v1
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
            - name: Install composer dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: composer install
            - name: Install gRPC extension
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: pecl install grpc
            - name: Install protobuf extension
              if: matrix.proto_c_ext
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: pecl install protobuf
            - name: Run script
              run: vendor/bin/phpunit --coverage-clover=coverage.xml

    style:
        runs-on: ubuntu-latest
        name: PHP Style Check
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: "7.4"
            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: composer install
            - name: Run Script
              run: vendor/bin/phpcs -s --standard=./ruleset.xml
